# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    download_event_attachments as download_event_attachments,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.skip import maybe_skip_df as maybe_skip_df
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from wt_task import task

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params_dict.get("get_timezone") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    get_event_data = (
        task(get_events)
        .validate()
        .set_task_instance_id("get_event_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=None,
            raise_on_empty=False,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_display_values=True,
            **(params_dict.get("get_event_data") or {}),
        )
        .call()
    )

    convert_to_user_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_event_data,
            timezone=get_timezone,
            columns=["time"],
            **(params_dict.get("convert_to_user_timezone") or {}),
        )
        .call()
    )

    extract_reported_by = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_to_user_timezone,
            column_name="reported_by",
            field_name_options=["name"],
            output_type="str",
            output_column_name="reported_by_name",
            **(params_dict.get("extract_reported_by") or {}),
        )
        .call()
    )

    extract_reported_by_subtype = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_reported_by_subtype")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_reported_by,
            column_name="reported_by",
            field_name_options=["subject_subtype"],
            output_type="str",
            output_column_name="reported_by_subtype",
            **(params_dict.get("extract_reported_by_subtype") or {}),
        )
        .call()
    )

    process_event_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("process_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_reported_by_subtype,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_event_details") or {}),
        )
        .call()
    )

    normalize_event_details = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_event_details,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=False,
            **(params_dict.get("normalize_event_details") or {}),
        )
        .call()
    )

    drop_event_details_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_event_details_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_event_details,
            prefix="event_details__",
            duplicate_strategy="suffix",
            **(params_dict.get("drop_event_details_prefix") or {}),
        )
        .call()
    )

    events_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("events_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="event_type",
            colormap="tab20b",
            output_column_name="event_type_colormap",
            df=drop_event_details_prefix,
            **(params_dict.get("events_colormap") or {}),
        )
        .call()
    )

    filter_events = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_colormap,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params_dict.get("filter_events") or {}),
        )
        .call()
    )

    process_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("process_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_events,
            rename_columns={"time": "event_time"},
            retain_columns=[],
            raise_if_not_found=True,
            **(params_dict.get("process_columns") or {}),
        )
        .call()
    )

    sql_query = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("sql_query")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=process_columns, **(params_dict.get("sql_query") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    events_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("events_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sql_query,
            time_col="event_time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("events_add_temporal_index") or {}),
        )
        .call()
    )

    split_event_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_event_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_add_temporal_index,
            groupers=groupers,
            **(params_dict.get("split_event_groups") or {}),
        )
        .call()
    )

    persist_events = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            **(params_dict.get("persist_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_event_groups)
    )

    skip_attachment_download = (
        task(maybe_skip_df)
        .validate()
        .set_task_instance_id("skip_attachment_download")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_event_data, **(params_dict.get("skip_attachment_download") or {})
        )
        .call()
    )

    download_attachments = (
        task(download_event_attachments)
        .validate()
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            use_index_as_id=False,
            event_gdf=skip_attachment_download,
            skip_download=False,
            attachments_subdir="attachments",
            **(params_dict.get("download_attachments") or {}),
        )
        .call()
    )

    skip_map_generation = (
        task(maybe_skip_df)
        .validate()
        .set_task_instance_id("skip_map_generation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("skip_map_generation") or {}))
        .mapvalues(argnames=["df"], argvalues=split_event_groups)
    )

    rename_display_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_display_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "serial_number": "Event Serial",
                "event_time": "Event Time",
                "event_type_display": "Event Type",
                "reported_by_name": "Reported By",
            },
            raise_if_not_found=True,
            **(params_dict.get("rename_display_columns") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=skip_map_generation)
    )

    set_events_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_events_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Events Map", **(params_dict.get("set_events_map_title") or {}))
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("base_map_defs") or {}))
        .call()
    )

    grouped_events_map_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("grouped_events_map_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "event_type_colormap", "get_radius": 5},
            legend={
                "label_column": "Event Type",
                "color_column": "event_type_colormap",
            },
            tooltip_columns=["Event Serial", "Event Time", "Event Type", "Reported By"],
            **(params_dict.get("grouped_events_map_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=rename_display_columns)
    )

    grouped_events_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("grouped_events_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Event Type",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_events_map_title,
            **(params_dict.get("grouped_events_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=grouped_events_map_layer)
    )

    grouped_events_ecomap_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("grouped_events_ecomap_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("grouped_events_ecomap_html_url") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=grouped_events_ecomap)
    )

    grouped_events_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("grouped_events_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_events_map_title,
            **(params_dict.get("grouped_events_map_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=grouped_events_ecomap_html_url)
    )

    grouped_events_map_widget_merge = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_events_map_widget_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=grouped_events_map_widget,
            **(params_dict.get("grouped_events_map_widget_merge") or {}),
        )
        .call()
    )

    events_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("events_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[grouped_events_map_widget_merge],
            groupers=groupers,
            time_range=time_range,
            **(params_dict.get("events_dashboard") or {}),
        )
        .call()
    )

    return events_dashboard
