# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
<<<<<<< HEAD
import os
from typing import Any
=======
import json
import os
>>>>>>> 0be1c94 (recompile)

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import (
    filter_by_geometry_type as filter_by_geometry_type,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.groupby import (
    groupbykey_passthrough_skip as groupbykey_passthrough_skip,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    download_grouped_event_attachments as download_grouped_event_attachments,
)
from ecoscope_workflows_ext_custom.tasks.io import (
<<<<<<< HEAD
    persist_grouped_dfs_for_results_download as persist_grouped_dfs_for_results_download,
=======
    persist_df_wrapper as persist_df_wrapper,
>>>>>>> 0be1c94 (recompile)
)
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.skip import maybe_skip_df as maybe_skip_df
from ecoscope_workflows_ext_custom.tasks.transformation import (
    apply_sql_query as apply_sql_query,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_duplicate_columns as drop_duplicate_columns,
)
<<<<<<< HEAD
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())
=======
from wt_task import task

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))
>>>>>>> 0be1c94 (recompile)

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(**(params.get("workflow_details") or {}))
=======
        .partial(**(params_dict.get("workflow_details") or {}))
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(time_format="%d %b %Y %H:%M:%S", **(params.get("time_range") or {}))
=======
        .partial(
            time_format="%d %b %Y %H:%M:%S", **(params_dict.get("time_range") or {})
        )
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
=======
        .partial(time_range=time_range, **(params_dict.get("get_timezone") or {}))
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(**(params.get("er_client_name") or {}))
=======
        .partial(**(params_dict.get("er_client_name") or {}))
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    get_event_data = (
        task(get_events)
        .validate()
        .set_task_instance_id("get_event_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=None,
            raise_on_empty=False,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_display_values=True,
<<<<<<< HEAD
            **(params.get("get_event_data") or {}),
=======
            **(params_dict.get("get_event_data") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    convert_to_user_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_to_user_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_event_data,
            timezone=get_timezone,
            columns=["time"],
            auto_detect=False,
<<<<<<< HEAD
            **(params.get("convert_to_user_timezone") or {}),
=======
            **(params_dict.get("convert_to_user_timezone") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    extract_reported_by = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_to_user_timezone,
            column_name="reported_by",
            field_name_options=["name"],
            output_type="str",
            output_column_name="reported_by_name",
<<<<<<< HEAD
            **(params.get("extract_reported_by") or {}),
=======
            **(params_dict.get("extract_reported_by") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    extract_reported_by_subtype = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_reported_by_subtype")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_reported_by,
            column_name="reported_by",
            field_name_options=["subject_subtype"],
            output_type="str",
            output_column_name="reported_by_subtype",
<<<<<<< HEAD
            **(params.get("extract_reported_by_subtype") or {}),
=======
            **(params_dict.get("extract_reported_by_subtype") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    process_event_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("process_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_reported_by_subtype,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
<<<<<<< HEAD
            **(params.get("process_event_details") or {}),
=======
            **(params_dict.get("process_event_details") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    normalize_event_details = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_event_details,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=False,
<<<<<<< HEAD
            **(params.get("normalize_event_details") or {}),
=======
            **(params_dict.get("normalize_event_details") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    drop_event_details_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_event_details_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_event_details,
            prefix="event_details__",
            duplicate_strategy="suffix",
<<<<<<< HEAD
            **(params.get("drop_event_details_prefix") or {}),
=======
            **(params_dict.get("drop_event_details_prefix") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    convert_event_details_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_event_details_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_event_details_prefix,
            timezone=get_timezone,
            columns=[],
            auto_detect=True,
<<<<<<< HEAD
            **(params.get("convert_event_details_timezone") or {}),
=======
            **(params_dict.get("convert_event_details_timezone") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    events_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("events_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="event_type",
            colormap="tab20b",
            output_column_name="event_type_colormap",
            df=convert_event_details_timezone,
<<<<<<< HEAD
            **(params.get("events_colormap") or {}),
=======
            **(params_dict.get("events_colormap") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    filter_events = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_colormap,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
<<<<<<< HEAD
            **(params.get("filter_events") or {}),
=======
            **(params_dict.get("filter_events") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    process_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("process_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_events,
            rename_columns={"time": "event_time"},
            retain_columns=[],
            raise_if_not_found=True,
<<<<<<< HEAD
            **(params.get("process_columns") or {}),
=======
            **(params_dict.get("process_columns") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    sql_query = (
        task(apply_sql_query)
        .validate()
        .set_task_instance_id("sql_query")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(df=process_columns, **(params.get("sql_query") or {}))
=======
        .partial(df=process_columns, **(params_dict.get("sql_query") or {}))
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(**(params.get("groupers") or {}))
=======
        .partial(**(params_dict.get("groupers") or {}))
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    events_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("events_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=sql_query,
            time_col="event_time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
<<<<<<< HEAD
            **(params.get("events_add_temporal_index") or {}),
=======
            **(params_dict.get("events_add_temporal_index") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    split_event_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_event_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_add_temporal_index,
            groupers=groupers,
<<<<<<< HEAD
            **(params.get("split_event_groups") or {}),
=======
            **(params_dict.get("split_event_groups") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    persist_events = (
<<<<<<< HEAD
        task(persist_grouped_dfs_for_results_download)
=======
        task(persist_df_wrapper)
>>>>>>> 0be1c94 (recompile)
        .validate()
        .set_task_instance_id("persist_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
<<<<<<< HEAD
            grouped_dfs=split_event_groups,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            **(params.get("persist_events") or {}),
        )
        .call()
=======
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            **(params_dict.get("persist_events") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_event_groups)
>>>>>>> 0be1c94 (recompile)
    )

    skip_attachment_download = (
        task(maybe_skip_df)
        .validate()
        .set_task_instance_id("skip_attachment_download")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(df=get_event_data, **(params.get("skip_attachment_download") or {}))
=======
        .partial(
            df=get_event_data, **(params_dict.get("skip_attachment_download") or {})
        )
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    download_attachments = (
        task(download_grouped_event_attachments)
        .validate()
        .set_task_instance_id("download_attachments")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            use_index_as_id=False,
            grouped_event_gdfs=skip_attachment_download,
            skip_download=False,
            attachments_subdir="attachments",
<<<<<<< HEAD
            **(params.get("download_attachments") or {}),
=======
            **(params_dict.get("download_attachments") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    skip_map_generation = (
        task(maybe_skip_df)
        .validate()
        .set_task_instance_id("skip_map_generation")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(**(params.get("skip_map_generation") or {}))
=======
        .partial(**(params_dict.get("skip_map_generation") or {}))
>>>>>>> 0be1c94 (recompile)
        .mapvalues(argnames=["df"], argvalues=split_event_groups)
    )

    dedup_columns = (
        task(drop_duplicate_columns)
        .validate()
        .set_task_instance_id("dedup_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(strategy="drop_last", **(params.get("dedup_columns") or {}))
=======
        .partial(strategy="drop_last", **(params_dict.get("dedup_columns") or {}))
>>>>>>> 0be1c94 (recompile)
        .mapvalues(argnames=["df"], argvalues=skip_map_generation)
    )

    rename_display_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_display_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "serial_number": "Event Serial",
                "event_time": "Event Time",
                "event_type_display": "Event Type",
                "reported_by_name": "Reported By",
            },
            raise_if_not_found=False,
<<<<<<< HEAD
            **(params.get("rename_display_columns") or {}),
=======
            **(params_dict.get("rename_display_columns") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .mapvalues(argnames=["df"], argvalues=dedup_columns)
    )

    filter_points_for_map = (
        task(filter_by_geometry_type)
        .validate()
        .set_task_instance_id("filter_points_for_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
<<<<<<< HEAD
<<<<<<< HEAD
            geometry_types=["Point"], **(params.get("filter_points_for_map") or {})
=======
            geometry_types=["Point"], **(params_dict.get("filter_points_for_map") or {})
>>>>>>> fe2bb0e (feat: polygon event support + ecoscope-platform 2.11.14 (#31))
=======
            geometry_types=["Point"], **(params_dict.get("filter_points_for_map") or {})
>>>>>>> 0be1c94 (recompile)
        )
        .mapvalues(argnames=["df"], argvalues=rename_display_columns)
    )

    filter_polygons_for_map = (
        task(filter_by_geometry_type)
        .validate()
        .set_task_instance_id("filter_polygons_for_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geometry_types=["Polygon", "MultiPolygon"],
<<<<<<< HEAD
<<<<<<< HEAD
            **(params.get("filter_polygons_for_map") or {}),
=======
            **(params_dict.get("filter_polygons_for_map") or {}),
>>>>>>> fe2bb0e (feat: polygon event support + ecoscope-platform 2.11.14 (#31))
=======
            **(params_dict.get("filter_polygons_for_map") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .mapvalues(argnames=["df"], argvalues=rename_display_columns)
    )

    set_events_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_events_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(var="Events Map", **(params.get("set_events_map_title") or {}))
=======
        .partial(var="Events Map", **(params_dict.get("set_events_map_title") or {}))
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
<<<<<<< HEAD
        .partial(**(params.get("base_map_defs") or {}))
=======
        .partial(**(params_dict.get("base_map_defs") or {}))
>>>>>>> 0be1c94 (recompile)
        .call()
    )

    grouped_events_map_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("grouped_events_map_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "event_type_colormap", "get_radius": 5},
            legend={
                "label_column": "Event Type",
                "color_column": "event_type_colormap",
            },
            tooltip_columns=["Event Serial", "Event Time", "Event Type", "Reported By"],
<<<<<<< HEAD
            **(params.get("grouped_events_map_layer") or {}),
=======
            **(params_dict.get("grouped_events_map_layer") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .mapvalues(argnames=["geodataframe"], argvalues=filter_points_for_map)
    )

    grouped_events_polygon_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("grouped_events_polygon_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "event_type_colormap",
                "stroked": True,
                "get_line_color": "white",
                "get_line_width": 2,
                "opacity": 0.4,
            },
            legend={
                "label_column": "Event Type",
                "color_column": "event_type_colormap",
            },
            tooltip_columns=["Event Serial", "Event Time", "Event Type", "Reported By"],
<<<<<<< HEAD
<<<<<<< HEAD
            **(params.get("grouped_events_polygon_layer") or {}),
=======
            **(params_dict.get("grouped_events_polygon_layer") or {}),
>>>>>>> fe2bb0e (feat: polygon event support + ecoscope-platform 2.11.14 (#31))
=======
            **(params_dict.get("grouped_events_polygon_layer") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .mapvalues(argnames=["geodataframe"], argvalues=filter_polygons_for_map)
    )

    combined_event_map_layers = (
        task(groupbykey_passthrough_skip)
        .validate()
        .set_task_instance_id("combined_event_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[grouped_events_polygon_layer, grouped_events_map_layer],
<<<<<<< HEAD
<<<<<<< HEAD
            **(params.get("combined_event_map_layers") or {}),
=======
            **(params_dict.get("combined_event_map_layers") or {}),
>>>>>>> fe2bb0e (feat: polygon event support + ecoscope-platform 2.11.14 (#31))
=======
            **(params_dict.get("combined_event_map_layers") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    grouped_events_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("grouped_events_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Event Type",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_events_map_title,
<<<<<<< HEAD
            **(params.get("grouped_events_ecomap") or {}),
=======
            **(params_dict.get("grouped_events_ecomap") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .mapvalues(argnames=["geo_layers"], argvalues=combined_event_map_layers)
    )

    grouped_events_ecomap_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("grouped_events_ecomap_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
<<<<<<< HEAD
            **(params.get("grouped_events_ecomap_html_url") or {}),
=======
            **(params_dict.get("grouped_events_ecomap_html_url") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .mapvalues(argnames=["text"], argvalues=grouped_events_ecomap)
    )

    grouped_events_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("grouped_events_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=set_events_map_title,
<<<<<<< HEAD
            **(params.get("grouped_events_map_widget") or {}),
=======
            **(params_dict.get("grouped_events_map_widget") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .map(argnames=["view", "data"], argvalues=grouped_events_ecomap_html_url)
    )

    grouped_events_map_widget_merge = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_events_map_widget_merge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=grouped_events_map_widget,
<<<<<<< HEAD
            **(params.get("grouped_events_map_widget_merge") or {}),
=======
            **(params_dict.get("grouped_events_map_widget_merge") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    events_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("events_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[grouped_events_map_widget_merge],
            groupers=groupers,
            time_range=time_range,
<<<<<<< HEAD
            **(params.get("events_dashboard") or {}),
=======
            **(params_dict.get("events_dashboard") or {}),
>>>>>>> 0be1c94 (recompile)
        )
        .call()
    )

    return events_dashboard
