time_range:
  since: "2025-08-01"
  until: "2025-08-31"
er_client_name:
  data_source:
    name: "mep_dev"
get_event_data:
  event_columns: ["id", "time", "event_type", "event_category", "reported_by", "serial_number", "geometry", "event_details"]
  event_types: ["arrest_rep", "snare_rep", "poacher_camp_rep"]
filter_events:
  bounding_box:
    min_x: 33.0
    min_y: -3.0
    max_x: 36.0
    max_y: 0.0
  filter_point_coords: [
    {"x": 180.0, "y": 90.0},
    {"x": 0.0, "y": 0.0},
    {"x": 1.0, "y": 1.0},
  ]
persist_events:
  filetypes: ["geoparquet", "csv"]
  sanitize: true # todo: make it default with rjsf override