# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Er Events
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    gather_output_files as gather_output_files,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_column as normalize_column,
)

# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(time_format="%Y-%m-%d", **time_range_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Get Event Data

# %%
# parameters

get_event_data_params = dict(
    event_types=...,
    event_columns=...,
    include_display_values=...,
)

# %%
# call the task


get_event_data = (
    get_events.set_task_instance_id("get_event_data")
    .handle_errors()
    .with_tracing()
    .partial(
        client=er_client_name,
        time_range=time_range,
        raise_on_empty=False,
        include_details=True,
        include_updates=False,
        include_related_events=False,
        include_null_geometry=True,
        **get_event_data_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Event Relocations

# %%
# parameters

filter_events_params = dict(
    bounding_box=...,
    filter_point_coords=...,
)

# %%
# call the task


filter_events = (
    apply_reloc_coord_filter.set_task_instance_id("filter_events")
    .handle_errors()
    .with_tracing()
    .partial(df=get_event_data, roi_gdf=None, roi_name=None, **filter_events_params)
    .call()
)


# %% [markdown]
# ## Normalize Event Details

# %%
# parameters

normalize_event_details_params = dict()

# %%
# call the task


normalize_event_details = (
    normalize_column.set_task_instance_id("normalize_event_details")
    .handle_errors()
    .with_tracing()
    .partial(df=filter_events, column="event_details", **normalize_event_details_params)
    .call()
)


# %% [markdown]
# ## Remove Column Prefix Event Details

# %%
# parameters

event_cleanup_params = dict()

# %%
# call the task


event_cleanup = (
    drop_column_prefix.set_task_instance_id("event_cleanup")
    .handle_errors()
    .with_tracing()
    .partial(
        df=normalize_event_details, prefix="event_details__", **event_cleanup_params
    )
    .call()
)


# %% [markdown]
# ## Persist Events

# %%
# parameters

persist_events_params = dict(
    filename=...,
    filetypes=...,
    sanitize=...,
)

# %%
# call the task


persist_events = (
    persist_df_wrapper.set_task_instance_id("persist_events")
    .handle_errors()
    .with_tracing()
    .partial(
        df=event_cleanup,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_events_params,
    )
    .call()
)


# %% [markdown]
# ## Gather Output Files

# %%
# parameters

output_files_params = dict()

# %%
# call the task


output_files = (
    gather_output_files.set_task_instance_id("output_files")
    .handle_errors()
    .with_tracing()
    .partial(files=persist_events, **output_files_params)
    .call()
)
